// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('MainPageNavigation', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('should navigate to all pages', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    await driver.findElement(By.css("app-summoner:nth-child(1)")).click()
    await driver.wait(until.urlContains("summoner"), 10000)
    await driver.findElement(By.linkText("Leaderboard")).click()
    await driver.wait(until.urlContains("/"), 10000)
    await driver.findElement(By.linkText("About")).click()
    await driver.wait(until.urlContains("about"), 10000)
    await driver.findElement(By.linkText("Contact")).click()
    await driver.wait(until.urlContains("contact"), 10000)
  })
})
